name: Java App CI/CD

on:
  push:
    branches:
      - main  # You can customize this to the branch you want to trigger the workflow.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/java-app .
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/java-app ${{ secrets.DOCKERHUB_USERNAME }}/java-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/java-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Pull and deploy Docker image
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/java-app:latest
          docker run -d -p 80:8080 ${{ secrets.DOCKERHUB_USERNAME }}/java-app:latest
        env:
          AWS_INSTANCE_IP: 54.242.12.102

